version: "3.6"
services:
    api:
        image: tiangolo/uwsgi-nginx-flask:python3.6
        container_name: api
        ports:
            - "8881:80"
        environment:
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
            - "RUN=flask run --host=0.0.0.0 --port=80"
        command: flask run --host=0.0.0.0 --port=80
        volumes:
            - ./app:/app
        networks:
            - back-tier
networks:
    back-tier:
